version: "3.8"  # optional since v1.27.0
services:
  locker-server:
    image: locker:test
    ports:
      - "27001:27001"
    environment: 
      - LOCKER_SERVER_IP="127.0.0.1"
      - LOCKER_SERVER_PORT="27001"
      - LOCKER_SERVER_LOG="./locker-server.log"
      - LOCKER_SERVER_ARTIFACTS_ROOT="/out"
    volumes:
      - ./out:/out
      - logvolume01:/var/log


volumes:
  logvolume01: {}
