// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: server/protobuf/messageSchema.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_META    MessageType = 0
	MessageType_PACKAGE MessageType = 1
	MessageType_ACK     MessageType = 2
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "META",
		1: "PACKAGE",
		2: "ACK",
	}
	MessageType_value = map[string]int32{
		"META":    0,
		"PACKAGE": 1,
		"ACK":     2,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_server_protobuf_messageSchema_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_server_protobuf_messageSchema_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_server_protobuf_messageSchema_proto_rawDescGZIP(), []int{0}
}

type FileInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MsgType MessageType `protobuf:"varint,2,opt,name=msgType,proto3,enum=protobuf.MessageType" json:"msgType,omitempty"`
	Payload string      `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_protobuf_messageSchema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_messageSchema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_server_protobuf_messageSchema_proto_rawDescGZIP(), []int{0}
}

func (x *FileInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FileInfo) GetMsgType() MessageType {
	if x != nil {
		return x.MsgType
	}
	return MessageType_META
}

func (x *FileInfo) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type TestMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	String_ string      `protobuf:"bytes,2,opt,name=string,proto3" json:"string,omitempty"`
	Uint    uint32      `protobuf:"varint,3,opt,name=uint,proto3" json:"uint,omitempty"`
	Enum    MessageType `protobuf:"varint,4,opt,name=enum,proto3,enum=protobuf.MessageType" json:"enum,omitempty"`
}

func (x *TestMessage) Reset() {
	*x = TestMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_protobuf_messageSchema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMessage) ProtoMessage() {}

func (x *TestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_server_protobuf_messageSchema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMessage.ProtoReflect.Descriptor instead.
func (*TestMessage) Descriptor() ([]byte, []int) {
	return file_server_protobuf_messageSchema_proto_rawDescGZIP(), []int{1}
}

func (x *TestMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TestMessage) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *TestMessage) GetUint() uint32 {
	if x != nil {
		return x.Uint
	}
	return 0
}

func (x *TestMessage) GetEnum() MessageType {
	if x != nil {
		return x.Enum
	}
	return MessageType_META
}

var File_server_protobuf_messageSchema_proto protoreflect.FileDescriptor

var file_server_protobuf_messageSchema_proto_rawDesc = []byte{
	0x0a, 0x23, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x53, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22,
	0x65, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2f, 0x0a, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x74, 0x0a, 0x0b, 0x54, 0x65, 0x73, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x75, 0x69, 0x6e,
	0x74, 0x12, 0x29, 0x0a, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x65, 0x6e, 0x75, 0x6d, 0x2a, 0x2d, 0x0a, 0x0b,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4d,
	0x45, 0x54, 0x41, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x41, 0x43, 0x4b, 0x41, 0x47, 0x45,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x4b, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_server_protobuf_messageSchema_proto_rawDescOnce sync.Once
	file_server_protobuf_messageSchema_proto_rawDescData = file_server_protobuf_messageSchema_proto_rawDesc
)

func file_server_protobuf_messageSchema_proto_rawDescGZIP() []byte {
	file_server_protobuf_messageSchema_proto_rawDescOnce.Do(func() {
		file_server_protobuf_messageSchema_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_protobuf_messageSchema_proto_rawDescData)
	})
	return file_server_protobuf_messageSchema_proto_rawDescData
}

var file_server_protobuf_messageSchema_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_protobuf_messageSchema_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_server_protobuf_messageSchema_proto_goTypes = []interface{}{
	(MessageType)(0),    // 0: protobuf.MessageType
	(*FileInfo)(nil),    // 1: protobuf.FileInfo
	(*TestMessage)(nil), // 2: protobuf.TestMessage
}
var file_server_protobuf_messageSchema_proto_depIdxs = []int32{
	0, // 0: protobuf.FileInfo.msgType:type_name -> protobuf.MessageType
	0, // 1: protobuf.TestMessage.enum:type_name -> protobuf.MessageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_protobuf_messageSchema_proto_init() }
func file_server_protobuf_messageSchema_proto_init() {
	if File_server_protobuf_messageSchema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_protobuf_messageSchema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_protobuf_messageSchema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_protobuf_messageSchema_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_protobuf_messageSchema_proto_goTypes,
		DependencyIndexes: file_server_protobuf_messageSchema_proto_depIdxs,
		EnumInfos:         file_server_protobuf_messageSchema_proto_enumTypes,
		MessageInfos:      file_server_protobuf_messageSchema_proto_msgTypes,
	}.Build()
	File_server_protobuf_messageSchema_proto = out.File
	file_server_protobuf_messageSchema_proto_rawDesc = nil
	file_server_protobuf_messageSchema_proto_goTypes = nil
	file_server_protobuf_messageSchema_proto_depIdxs = nil
}
